-- OfferTamizha production database schema
-- Run this once in Supabase > SQL Editor.
-- Then create your admin user in Authentication > Users and add that email to public.admin_users.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_offer_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email',''))
  );
$$;

revoke all on function public.is_offer_admin() from public;
grant execute on function public.is_offer_admin() to authenticated;

create table if not exists public.deals (
  id bigint generated by default as identity primary key,
  title text not null,
  store text not null default 'Amazon',
  category text not null,
  emoji text default '🛍️',
  image text default '',
  old_price numeric(12,2) not null default 0,
  price numeric(12,2) not null default 0,
  rating numeric(2,1) not null default 4.4,
  reviews text default '0',
  discount integer not null default 0,
  href text not null default '#',
  description text default '',
  button_label text default 'View Deal',
  active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists deals_active_idx on public.deals(active);
create index if not exists deals_category_idx on public.deals(category);
create index if not exists deals_store_idx on public.deals(store);
alter table public.deals enable row level security;

drop policy if exists "public read active deals" on public.deals;
create policy "public read active deals" on public.deals for select to anon using (active = true);
drop policy if exists "authenticated read deals" on public.deals;
create policy "authenticated read deals" on public.deals for select to authenticated using (active = true or public.is_offer_admin());
drop policy if exists "admin insert deals" on public.deals;
create policy "admin insert deals" on public.deals for insert to authenticated with check (public.is_offer_admin());
drop policy if exists "admin update deals" on public.deals;
create policy "admin update deals" on public.deals for update to authenticated using (public.is_offer_admin()) with check (public.is_offer_admin());
drop policy if exists "admin delete deals" on public.deals;
create policy "admin delete deals" on public.deals for delete to authenticated using (public.is_offer_admin());

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  is_public boolean not null default true,
  updated_at timestamptz not null default now()
);
alter table public.site_settings enable row level security;
drop policy if exists "public read public settings" on public.site_settings;
create policy "public read public settings" on public.site_settings for select to anon using (is_public = true);
drop policy if exists "authenticated read settings" on public.site_settings;
create policy "authenticated read settings" on public.site_settings for select to authenticated using (is_public = true or public.is_offer_admin());
drop policy if exists "admin manage settings" on public.site_settings;
create policy "admin manage settings" on public.site_settings for all to authenticated using (public.is_offer_admin()) with check (public.is_offer_admin());

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text default '',
  image text not null,
  href text default '#',
  cta text default 'View Deal',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.banners enable row level security;
drop policy if exists "public read active banners" on public.banners;
create policy "public read active banners" on public.banners for select to anon using (active = true);
drop policy if exists "authenticated read banners" on public.banners;
create policy "authenticated read banners" on public.banners for select to authenticated using (active = true or public.is_offer_admin());
drop policy if exists "admin manage banners" on public.banners;
create policy "admin manage banners" on public.banners for all to authenticated using (public.is_offer_admin()) with check (public.is_offer_admin());

create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique,
  created_at timestamptz not null default now()
);
alter table public.visitors enable row level security;
drop policy if exists "public create visitor" on public.visitors;
create policy "public create visitor" on public.visitors for insert to anon, authenticated with check (true);
drop policy if exists "admin read visitors" on public.visitors;
create policy "admin read visitors" on public.visitors for select to authenticated using (public.is_offer_admin());

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  path text default '/',
  created_at timestamptz not null default now()
);
create index if not exists page_views_created_idx on public.page_views(created_at desc);
alter table public.page_views enable row level security;
drop policy if exists "public record page views" on public.page_views;
create policy "public record page views" on public.page_views for insert to anon, authenticated with check (true);
drop policy if exists "admin read page views" on public.page_views;
create policy "admin read page views" on public.page_views for select to authenticated using (public.is_offer_admin());

create table if not exists public.click_events (
  id bigint generated by default as identity primary key,
  deal_id bigint references public.deals(id) on delete set null,
  visitor_id text,
  created_at timestamptz not null default now()
);
create index if not exists click_events_created_idx on public.click_events(created_at desc);
create index if not exists click_events_deal_idx on public.click_events(deal_id);
alter table public.click_events enable row level security;
drop policy if exists "public record clicks" on public.click_events;
create policy "public record clicks" on public.click_events for insert to anon, authenticated with check (true);
drop policy if exists "admin read clicks" on public.click_events;
create policy "admin read clicks" on public.click_events for select to authenticated using (public.is_offer_admin());

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  entity text,
  detail text,
  tone text default 'green',
  created_at timestamptz not null default now()
);
alter table public.activity_logs enable row level security;
drop policy if exists "admin read activity" on public.activity_logs;
create policy "admin read activity" on public.activity_logs for select to authenticated using (public.is_offer_admin());
drop policy if exists "admin write activity" on public.activity_logs;
create policy "admin write activity" on public.activity_logs for insert to authenticated with check (public.is_offer_admin());

-- API privileges. RLS policies above still control which rows each role can use.
grant select on public.deals, public.site_settings, public.banners to anon, authenticated;
grant insert on public.visitors, public.page_views, public.click_events to anon, authenticated;
grant select on public.visitors, public.page_views, public.click_events, public.activity_logs to authenticated;
grant insert, update, delete on public.deals, public.site_settings, public.banners to authenticated;
grant insert on public.activity_logs to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.site_settings(key,value,is_public) values
  ('siteName','OfferTamizha',true),
  ('tagline','Deals in Tamil • Save More • Live Better',true),
  ('telegramUrl','https://t.me/OffersTamizha1',true),
  ('instagramUrl','https://www.instagram.com/offerstamizha/',true),
  ('youtubeUrl','https://youtube.com/@offertamizha',true),
  ('supportEmail','support@offertamizha.com',true),
  ('seoTitle','OfferTamizha - Best Online Deals in Tamil',true),
  ('seoDescription','Smart shopping deals from leading Indian marketplaces, curated for Tamil shoppers.',true),
  ('primaryColor','#ff5a00',true)
on conflict (key) do nothing;

-- Starter deals. Replace href '#' with your real affiliate URLs from the Admin dashboard.
insert into public.deals (id,title,store,category,emoji,old_price,price,rating,reviews,discount,href,description,button_label,active,featured) values
(1,'Women''s Ethnic Kurti Set','Meesho','Fashion','👗',999,399,4.4,'2.1K',60,'#','Stylish & Comfortable','View Deal',true,true),
(2,'Wireless Bluetooth Earbuds','Amazon','Electronics','🎧',2999,999,4.3,'5.2K',67,'#','Premium Sound','View Deal',true,true),
(3,'Portable Mini Blender','Flipkart','Home & Kitchen','🥤',1599,799,4.2,'1.1K',50,'#','Compact kitchen helper','View Deal',true,false),
(4,'Smart Watch for Men','Amazon','Electronics','⌚',1799,499,4.4,'3.8K',72,'#','Bluetooth Calling','View Deal',true,true),
(5,'Skincare Combo Set','Myntra','Beauty','🧴',949,399,4.3,'2.9K',58,'#','Daily skincare combo','View Deal',true,false),
(6,'Home Storage Organizer','Meesho','Home & Kitchen','🧺',1299,449,4.5,'4.4K',65,'#','Smart home storage','View Deal',true,false),
(7,'Running Shoes','Flipkart','Fashion','👟',2299,1099,4.3,'8.2K',52,'#','Lightweight & stylish','View Deal',true,false),
(8,'Premium Travel Backpack','Amazon','Fashion','🎒',1899,799,4.6,'6.6K',58,'#','Travel-ready backpack','View Deal',true,false),
(9,'Mixer Grinder 750W','Croma','Home & Kitchen','⚙️',4999,2999,4.2,'990',40,'#','Powerful mixer grinder','View Deal',true,false),
(10,'Casual Cotton T-Shirt','Myntra','Fashion','👕',1299,499,4.1,'1.7K',62,'#','Comfortable casual wear','View Deal',true,false),
(11,'Wireless Keyboard & Mouse','Amazon','Electronics','⌨️',2499,1199,4.4,'3.4K',52,'#','Wireless work setup','View Deal',true,false),
(12,'Makeup Essentials Kit','Ajio','Beauty','💄',1999,899,4.5,'2.5K',55,'#','Everyday makeup essentials','View Deal',true,false)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.deals','id'), greatest((select coalesce(max(id),1) from public.deals),1), true);

-- IMPORTANT: after creating your Supabase Auth user, run this with your real admin email:
-- insert into public.admin_users(email) values ('your-admin@email.com') on conflict do nothing;
